language: python
python:
  - "2.7"
install:
  - "pip install tox flake8 python-coveralls"
  - "ci/travis.sh"
script: tox && python setup.py nosetests
notifications:
  slack: cocaine:qDewv6ZVDt0TciQeNdE47GqG
branches:
  only:
    - v0.11
    - master
after_success: coveralls
