language: python
python:
  - "2.7"
install:
  - "pip install tox"
  - "pip install flake8"
script: tox
notifications:
  slack: cocaine:qDewv6ZVDt0TciQeNdE47GqG
branches:
  only:
    - master
    - v0.11
